modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1は47.x系
license="MIT"
[[mods]]
modId="jidoumodel"
version="1.0.0"
displayName="jidoumodel"
authors="sakalti"
description='''jidoumodelの説明をここに書いてください'''

[[dependencies.jidoumodel]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jidoumodel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
