modLoader="javafml"
loaderVersion="[43,)" # 1.19.2 Forgeは43.x系
license="MIT"
[[mods]]
modId="jidoumodel"
version="1.0.0"
displayName="jidoumodel"
authors="sakalti"
description='''jidoumodelの説明をここに書きます'''

# 依存関係例
[[dependencies.jidoumodel]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jidoumodel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
